### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by leovarmak** [ziishaned/define-cli#2]
I get an error saying there is a syntax error even tho there isn't one

![image](https://user-images.githubusercontent.com/14135553/53684978-7dd4b400-3d3a-11e9-9936-0cb807ef42c2.png)

**Comment by pavanjadhaw** [comment]
That should be fixed after above pull request gets merged(hopefully)

**Comment by hos4m** [comment]
+1

**Comment by ice1080** [comment]
I seem to be getting the same thing:
`$ sudo npm install -g define-cli
Password:
/usr/local/bin/define -> /usr/local/lib/node_modules/define-cli/index.js
+ define-cli@0.0.7
added 43 packages from 73 contributors in 2.577s
$ define intelligent
/usr/local/bin/define: line 1: syntax error near unexpected token `('
/usr/local/bin/define: line 1: `const ora = require('ora');'`
