### ISSUE TITLE
Not working on mac OS

### ISSUE THREAD

**Issue by ilearnio** [ziishaned/define-cli#6]
This line `#!/usr/bin/env node` was missing in my `/usr/local/bin/define` js file, which is needed on Mac and Linux for non-compiled binaries.

Amazing idea and implementation BTW!

**UPDATED:**
it was giving me this error which disappeared after I added that line
```
→ define word
/usr/local/bin/define: line 1: syntax error near unexpected token `('
/usr/local/bin/define: line 1: `const ora = require('ora');'
```

**Comment by pavanjadhaw** [comment]
Yeah expected, https://github.com/ziishaned/define-cli/pull/4

**Comment by ilearnio** [comment]
Oh, I see. Closing then
